/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F4XX.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//int main(void)

    /* Loop forever */
	/*for(;;);
	/*GPIO_Handle_t GpioLed;
	GpioLed.pGPIOx = GPIOd;
	GpioLed.PIN_CONFIG.GPIO_PinNumber=GPIO_PinNumber_15;
	GpioLed.PIN_CONFIG.GPIO_PinMode=GPIO_PinMode_OUT;
	GpioLed.PIN_CONFIG.GPIO_PinSpeed=GPIO_PinSpeed_FAST;
	GpioLed.PIN_CONFIG.GPIO_PinOPType=GPIO_OUT_PP;
	GpioLed.PIN_CONFIG.GPIO_PinPuPdControl=GPIO_PIN_PU;	*/

